// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/envelope/v1/envelope.proto

// Package batch2go.envelope.v1 is the proxy↔adapter transport contract.
//
// It is versioned independently of the Triton API, because it is part of the
// treatment: Factor A is exactly the question of whether a cohort's B logical
// requests travel in one of these or in B of them. Serialization cost is a
// declared constituent of the measured effect, so the wire shape is pinned
// rather than left to convenience (ADR-0003).

package envelopev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is one logical request's terminal outcome. A member that failed is
// reported as failed; it never disappears from the response.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERROR       Status = 2
	Status_STATUS_TIMEOUT     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_TIMEOUT",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_TIMEOUT":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_envelope_v1_envelope_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_envelope_v1_envelope_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{0}
}

// LogicalRequest is one unit of work as the client sees it, carrying the
// identity minted by the load generator unchanged.
type LogicalRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CohortId uint32                 `protobuf:"varint,1,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	Ordinal  uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	// uid is what the model consumes and returns tiled, so membership is attested
	// by the model rather than inferred (ADR-0007). It is derived from the
	// identity above and carried so the adapter never has to re-derive it.
	Uid int64 `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	// payload is the declared padding input. It is a bytes field so that
	// serialization is a single copy out of a preallocated buffer, and it travels
	// every hop because payload size has to be realized on all of them — including
	// host-to-device staging, which is why the model consumes it rather than the
	// adapter stripping it (M1 §4).
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalRequest) Reset() {
	*x = LogicalRequest{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalRequest) ProtoMessage() {}

func (x *LogicalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalRequest.ProtoReflect.Descriptor instead.
func (*LogicalRequest) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *LogicalRequest) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *LogicalRequest) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *LogicalRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *LogicalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// RequestEnvelope is one transport message from proxy to adapter: one logical
// request at A=off, a whole cohort at A=on.
type RequestEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ExperimentId  string                 `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Cell          string                 `protobuf:"bytes,5,opt,name=cell,proto3" json:"cell,omitempty"`
	ClockDomainId string                 `protobuf:"bytes,6,opt,name=clock_domain_id,json=clockDomainId,proto3" json:"clock_domain_id,omitempty"`
	CohortId      uint32                 `protobuf:"varint,7,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	EnvelopeId    uint64                 `protobuf:"varint,8,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	// The assigned factor levels. They are carried so the adapter acts on what the
	// manifest declared rather than on what the envelope's shape suggests: a
	// one-request envelope is not evidence of A=off.
	Aggregate bool `protobuf:"varint,9,opt,name=aggregate,proto3" json:"aggregate,omitempty"`
	Vectorize bool `protobuf:"varint,10,opt,name=vectorize,proto3" json:"vectorize,omitempty"`
	// target_b is the cohort size the run declared, and expected_members what this
	// envelope should contain. The adapter validates one against the other rather
	// than trusting the count it happens to receive.
	TargetB         uint32            `protobuf:"varint,11,opt,name=target_b,json=targetB,proto3" json:"target_b,omitempty"`
	ExpectedMembers uint32            `protobuf:"varint,12,opt,name=expected_members,json=expectedMembers,proto3" json:"expected_members,omitempty"`
	Requests        []*LogicalRequest `protobuf:"bytes,13,rep,name=requests,proto3" json:"requests,omitempty"`
	// t_proxy_send is the proxy's own monotonic timestamp at the moment of send,
	// and t_cohort_seal is carried only at A=on, where the proxy owns the seal. At
	// A=off the proxy does no joining and emits no seal (ADR-0001).
	TProxySend  int64  `protobuf:"varint,14,opt,name=t_proxy_send,json=tProxySend,proto3" json:"t_proxy_send,omitempty"`
	TCohortSeal *int64 `protobuf:"varint,15,opt,name=t_cohort_seal,json=tCohortSeal,proto3,oneof" json:"t_cohort_seal,omitempty"`
	// Byte accounting, measured rather than assumed.
	LogicalBytes   uint64 `protobuf:"varint,16,opt,name=logical_bytes,json=logicalBytes,proto3" json:"logical_bytes,omitempty"`
	AuxiliaryBytes uint64 `protobuf:"varint,17,opt,name=auxiliary_bytes,json=auxiliaryBytes,proto3" json:"auxiliary_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestEnvelope) Reset() {
	*x = RequestEnvelope{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEnvelope) ProtoMessage() {}

func (x *RequestEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEnvelope.ProtoReflect.Descriptor instead.
func (*RequestEnvelope) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{1}
}

func (x *RequestEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RequestEnvelope) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *RequestEnvelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RequestEnvelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RequestEnvelope) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *RequestEnvelope) GetClockDomainId() string {
	if x != nil {
		return x.ClockDomainId
	}
	return ""
}

func (x *RequestEnvelope) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *RequestEnvelope) GetEnvelopeId() uint64 {
	if x != nil {
		return x.EnvelopeId
	}
	return 0
}

func (x *RequestEnvelope) GetAggregate() bool {
	if x != nil {
		return x.Aggregate
	}
	return false
}

func (x *RequestEnvelope) GetVectorize() bool {
	if x != nil {
		return x.Vectorize
	}
	return false
}

func (x *RequestEnvelope) GetTargetB() uint32 {
	if x != nil {
		return x.TargetB
	}
	return 0
}

func (x *RequestEnvelope) GetExpectedMembers() uint32 {
	if x != nil {
		return x.ExpectedMembers
	}
	return 0
}

func (x *RequestEnvelope) GetRequests() []*LogicalRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

func (x *RequestEnvelope) GetTProxySend() int64 {
	if x != nil {
		return x.TProxySend
	}
	return 0
}

func (x *RequestEnvelope) GetTCohortSeal() int64 {
	if x != nil && x.TCohortSeal != nil {
		return *x.TCohortSeal
	}
	return 0
}

func (x *RequestEnvelope) GetLogicalBytes() uint64 {
	if x != nil {
		return x.LogicalBytes
	}
	return 0
}

func (x *RequestEnvelope) GetAuxiliaryBytes() uint64 {
	if x != nil {
		return x.AuxiliaryBytes
	}
	return 0
}

// LogicalResult is one member's outcome and the evidence its execution produced.
type LogicalResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	CohortId uint32                 `protobuf:"varint,1,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	Ordinal  uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Status   Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=batch2go.envelope.v1.Status" json:"status,omitempty"`
	Error    string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// membership_uids is the complete uid set the execution attested to, and
	// batch_size its realized shape. Both are evidence; neither is a conclusion.
	MembershipUids []int64 `protobuf:"varint,5,rep,packed,name=membership_uids,json=membershipUids,proto3" json:"membership_uids,omitempty"`
	BatchSize      uint32  `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	DataOutBytes   uint64  `protobuf:"varint,7,opt,name=data_out_bytes,json=dataOutBytes,proto3" json:"data_out_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogicalResult) Reset() {
	*x = LogicalResult{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalResult) ProtoMessage() {}

func (x *LogicalResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalResult.ProtoReflect.Descriptor instead.
func (*LogicalResult) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{2}
}

func (x *LogicalResult) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *LogicalResult) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *LogicalResult) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *LogicalResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *LogicalResult) GetMembershipUids() []int64 {
	if x != nil {
		return x.MembershipUids
	}
	return nil
}

func (x *LogicalResult) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *LogicalResult) GetDataOutBytes() uint64 {
	if x != nil {
		return x.DataOutBytes
	}
	return 0
}

// AdapterEvidence is what the adapter observed about its own dispatch. It never
// includes a conclusion about conformance, which the validator computes offline.
type AdapterEvidence struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Dispatched uint32                 `protobuf:"varint,1,opt,name=dispatched,proto3" json:"dispatched,omitempty"`
	// dispatch_skew_nanos is first-to-last submit within one fan-out call. It is
	// meaningful only when the adapter released more than one member at once, and
	// is recorded as zero otherwise rather than omitted.
	DispatchSkewNanos int64 `protobuf:"varint,2,opt,name=dispatch_skew_nanos,json=dispatchSkewNanos,proto3" json:"dispatch_skew_nanos,omitempty"`
	// cpu_nanos is the adapter's cost for this dispatch and cpu_scope says what
	// that number counted. The scope travels with the value because a quantity
	// whose definition changes between experimental conditions is not a
	// measurement of those conditions: the process scope counts the same work once
	// per concurrent dispatch, so it is comparable within a Factor A level and not
	// across one.
	CpuNanos      int64  `protobuf:"varint,3,opt,name=cpu_nanos,json=cpuNanos,proto3" json:"cpu_nanos,omitempty"`
	CpuScope      string `protobuf:"bytes,4,opt,name=cpu_scope,json=cpuScope,proto3" json:"cpu_scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterEvidence) Reset() {
	*x = AdapterEvidence{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterEvidence) ProtoMessage() {}

func (x *AdapterEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterEvidence.ProtoReflect.Descriptor instead.
func (*AdapterEvidence) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterEvidence) GetDispatched() uint32 {
	if x != nil {
		return x.Dispatched
	}
	return 0
}

func (x *AdapterEvidence) GetDispatchSkewNanos() int64 {
	if x != nil {
		return x.DispatchSkewNanos
	}
	return 0
}

func (x *AdapterEvidence) GetCpuNanos() int64 {
	if x != nil {
		return x.CpuNanos
	}
	return 0
}

func (x *AdapterEvidence) GetCpuScope() string {
	if x != nil {
		return x.CpuScope
	}
	return ""
}

// ResponseEnvelope carries the same identity back, with per-member results.
type ResponseEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CohortId      uint32                 `protobuf:"varint,3,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	EnvelopeId    uint64                 `protobuf:"varint,4,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	Results       []*LogicalResult       `protobuf:"bytes,5,rep,name=results,proto3" json:"results,omitempty"`
	Evidence      *AdapterEvidence       `protobuf:"bytes,6,opt,name=evidence,proto3" json:"evidence,omitempty"`
	TAdapterRecv  int64                  `protobuf:"varint,7,opt,name=t_adapter_recv,json=tAdapterRecv,proto3" json:"t_adapter_recv,omitempty"`
	TAdapterSend  int64                  `protobuf:"varint,8,opt,name=t_adapter_send,json=tAdapterSend,proto3" json:"t_adapter_send,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseEnvelope) Reset() {
	*x = ResponseEnvelope{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEnvelope) ProtoMessage() {}

func (x *ResponseEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEnvelope.ProtoReflect.Descriptor instead.
func (*ResponseEnvelope) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseEnvelope) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *ResponseEnvelope) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ResponseEnvelope) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *ResponseEnvelope) GetEnvelopeId() uint64 {
	if x != nil {
		return x.EnvelopeId
	}
	return 0
}

func (x *ResponseEnvelope) GetResults() []*LogicalResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ResponseEnvelope) GetEvidence() *AdapterEvidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *ResponseEnvelope) GetTAdapterRecv() int64 {
	if x != nil {
		return x.TAdapterRecv
	}
	return 0
}

func (x *ResponseEnvelope) GetTAdapterSend() int64 {
	if x != nil {
		return x.TAdapterSend
	}
	return 0
}

// ClientRequest is what the load generator sends to the proxy: one logical
// request over one stable client protocol, whatever the cell's Factor A level.
// The proxy, not the client, decides whether requests share an envelope.
type ClientRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	RunId    string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	CohortId uint32                 `protobuf:"varint,2,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	Ordinal  uint32                 `protobuf:"varint,3,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Uid      int64                  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Payload  []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	// t_cohort_seal is the barrier release instant, carried at A=off because the
	// load generator owns the seal there and the proxy records it on the client's
	// behalf (ADR-0001).
	TCohortSeal   *int64 `protobuf:"varint,6,opt,name=t_cohort_seal,json=tCohortSeal,proto3,oneof" json:"t_cohort_seal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{5}
}

func (x *ClientRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ClientRequest) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *ClientRequest) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ClientRequest) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ClientRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientRequest) GetTCohortSeal() int64 {
	if x != nil && x.TCohortSeal != nil {
		return *x.TCohortSeal
	}
	return 0
}

// ClientResponse is one logical request's result as the client sees it.
type ClientResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CohortId       uint32                 `protobuf:"varint,1,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	Ordinal        uint32                 `protobuf:"varint,2,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	Status         Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=batch2go.envelope.v1.Status" json:"status,omitempty"`
	Error          string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	MembershipUids []int64                `protobuf:"varint,5,rep,packed,name=membership_uids,json=membershipUids,proto3" json:"membership_uids,omitempty"`
	BatchSize      uint32                 `protobuf:"varint,6,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	DataOutBytes   uint64                 `protobuf:"varint,7,opt,name=data_out_bytes,json=dataOutBytes,proto3" json:"data_out_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_envelope_v1_envelope_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_api_envelope_v1_envelope_proto_rawDescGZIP(), []int{6}
}

func (x *ClientResponse) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *ClientResponse) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *ClientResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *ClientResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ClientResponse) GetMembershipUids() []int64 {
	if x != nil {
		return x.MembershipUids
	}
	return nil
}

func (x *ClientResponse) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *ClientResponse) GetDataOutBytes() uint64 {
	if x != nil {
		return x.DataOutBytes
	}
	return 0
}

var File_api_envelope_v1_envelope_proto protoreflect.FileDescriptor

const file_api_envelope_v1_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/envelope/v1/envelope.proto\x12\x14batch2go.envelope.v1\"s\n" +
	"\x0eLogicalRequest\x12\x1b\n" +
	"\tcohort_id\x18\x01 \x01(\rR\bcohortId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\x03R\x03uid\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\xfc\x04\n" +
	"\x0fRequestEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x12\n" +
	"\x04cell\x18\x05 \x01(\tR\x04cell\x12&\n" +
	"\x0fclock_domain_id\x18\x06 \x01(\tR\rclockDomainId\x12\x1b\n" +
	"\tcohort_id\x18\a \x01(\rR\bcohortId\x12\x1f\n" +
	"\venvelope_id\x18\b \x01(\x04R\n" +
	"envelopeId\x12\x1c\n" +
	"\taggregate\x18\t \x01(\bR\taggregate\x12\x1c\n" +
	"\tvectorize\x18\n" +
	" \x01(\bR\tvectorize\x12\x19\n" +
	"\btarget_b\x18\v \x01(\rR\atargetB\x12)\n" +
	"\x10expected_members\x18\f \x01(\rR\x0fexpectedMembers\x12@\n" +
	"\brequests\x18\r \x03(\v2$.batch2go.envelope.v1.LogicalRequestR\brequests\x12 \n" +
	"\ft_proxy_send\x18\x0e \x01(\x03R\n" +
	"tProxySend\x12'\n" +
	"\rt_cohort_seal\x18\x0f \x01(\x03H\x00R\vtCohortSeal\x88\x01\x01\x12#\n" +
	"\rlogical_bytes\x18\x10 \x01(\x04R\flogicalBytes\x12'\n" +
	"\x0fauxiliary_bytes\x18\x11 \x01(\x04R\x0eauxiliaryBytesB\x10\n" +
	"\x0e_t_cohort_seal\"\x84\x02\n" +
	"\rLogicalResult\x12\x1b\n" +
	"\tcohort_id\x18\x01 \x01(\rR\bcohortId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.batch2go.envelope.v1.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12+\n" +
	"\x0fmembership_uids\x18\x05 \x03(\x03B\x02\x10\x01R\x0emembershipUids\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x06 \x01(\rR\tbatchSize\x12$\n" +
	"\x0edata_out_bytes\x18\a \x01(\x04R\fdataOutBytes\"\x9b\x01\n" +
	"\x0fAdapterEvidence\x12\x1e\n" +
	"\n" +
	"dispatched\x18\x01 \x01(\rR\n" +
	"dispatched\x12.\n" +
	"\x13dispatch_skew_nanos\x18\x02 \x01(\x03R\x11dispatchSkewNanos\x12\x1b\n" +
	"\tcpu_nanos\x18\x03 \x01(\x03R\bcpuNanos\x12\x1b\n" +
	"\tcpu_scope\x18\x04 \x01(\tR\bcpuScope\"\xdc\x02\n" +
	"\x10ResponseEnvelope\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1b\n" +
	"\tcohort_id\x18\x03 \x01(\rR\bcohortId\x12\x1f\n" +
	"\venvelope_id\x18\x04 \x01(\x04R\n" +
	"envelopeId\x12=\n" +
	"\aresults\x18\x05 \x03(\v2#.batch2go.envelope.v1.LogicalResultR\aresults\x12A\n" +
	"\bevidence\x18\x06 \x01(\v2%.batch2go.envelope.v1.AdapterEvidenceR\bevidence\x12$\n" +
	"\x0et_adapter_recv\x18\a \x01(\x03R\ftAdapterRecv\x12$\n" +
	"\x0et_adapter_send\x18\b \x01(\x03R\ftAdapterSend\"\xc4\x01\n" +
	"\rClientRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1b\n" +
	"\tcohort_id\x18\x02 \x01(\rR\bcohortId\x12\x18\n" +
	"\aordinal\x18\x03 \x01(\rR\aordinal\x12\x10\n" +
	"\x03uid\x18\x04 \x01(\x03R\x03uid\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12'\n" +
	"\rt_cohort_seal\x18\x06 \x01(\x03H\x00R\vtCohortSeal\x88\x01\x01B\x10\n" +
	"\x0e_t_cohort_seal\"\x85\x02\n" +
	"\x0eClientResponse\x12\x1b\n" +
	"\tcohort_id\x18\x01 \x01(\rR\bcohortId\x12\x18\n" +
	"\aordinal\x18\x02 \x01(\rR\aordinal\x124\n" +
	"\x06status\x18\x03 \x01(\x0e2\x1c.batch2go.envelope.v1.StatusR\x06status\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12+\n" +
	"\x0fmembership_uids\x18\x05 \x03(\x03B\x02\x10\x01R\x0emembershipUids\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x06 \x01(\rR\tbatchSize\x12$\n" +
	"\x0edata_out_bytes\x18\a \x01(\x04R\fdataOutBytes*U\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x032e\n" +
	"\aBackend\x12Z\n" +
	"\aExecute\x12%.batch2go.envelope.v1.RequestEnvelope\x1a&.batch2go.envelope.v1.ResponseEnvelope\"\x002^\n" +
	"\x05Proxy\x12U\n" +
	"\x06Submit\x12#.batch2go.envelope.v1.ClientRequest\x1a$.batch2go.envelope.v1.ClientResponse\"\x00B=Z;github.com/matthewhoung/batch2go/api/envelope/v1;envelopev1b\x06proto3"

var (
	file_api_envelope_v1_envelope_proto_rawDescOnce sync.Once
	file_api_envelope_v1_envelope_proto_rawDescData []byte
)

func file_api_envelope_v1_envelope_proto_rawDescGZIP() []byte {
	file_api_envelope_v1_envelope_proto_rawDescOnce.Do(func() {
		file_api_envelope_v1_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_envelope_v1_envelope_proto_rawDesc), len(file_api_envelope_v1_envelope_proto_rawDesc)))
	})
	return file_api_envelope_v1_envelope_proto_rawDescData
}

var file_api_envelope_v1_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_envelope_v1_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_envelope_v1_envelope_proto_goTypes = []any{
	(Status)(0),              // 0: batch2go.envelope.v1.Status
	(*LogicalRequest)(nil),   // 1: batch2go.envelope.v1.LogicalRequest
	(*RequestEnvelope)(nil),  // 2: batch2go.envelope.v1.RequestEnvelope
	(*LogicalResult)(nil),    // 3: batch2go.envelope.v1.LogicalResult
	(*AdapterEvidence)(nil),  // 4: batch2go.envelope.v1.AdapterEvidence
	(*ResponseEnvelope)(nil), // 5: batch2go.envelope.v1.ResponseEnvelope
	(*ClientRequest)(nil),    // 6: batch2go.envelope.v1.ClientRequest
	(*ClientResponse)(nil),   // 7: batch2go.envelope.v1.ClientResponse
}
var file_api_envelope_v1_envelope_proto_depIdxs = []int32{
	1, // 0: batch2go.envelope.v1.RequestEnvelope.requests:type_name -> batch2go.envelope.v1.LogicalRequest
	0, // 1: batch2go.envelope.v1.LogicalResult.status:type_name -> batch2go.envelope.v1.Status
	3, // 2: batch2go.envelope.v1.ResponseEnvelope.results:type_name -> batch2go.envelope.v1.LogicalResult
	4, // 3: batch2go.envelope.v1.ResponseEnvelope.evidence:type_name -> batch2go.envelope.v1.AdapterEvidence
	0, // 4: batch2go.envelope.v1.ClientResponse.status:type_name -> batch2go.envelope.v1.Status
	2, // 5: batch2go.envelope.v1.Backend.Execute:input_type -> batch2go.envelope.v1.RequestEnvelope
	6, // 6: batch2go.envelope.v1.Proxy.Submit:input_type -> batch2go.envelope.v1.ClientRequest
	5, // 7: batch2go.envelope.v1.Backend.Execute:output_type -> batch2go.envelope.v1.ResponseEnvelope
	7, // 8: batch2go.envelope.v1.Proxy.Submit:output_type -> batch2go.envelope.v1.ClientResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_envelope_v1_envelope_proto_init() }
func file_api_envelope_v1_envelope_proto_init() {
	if File_api_envelope_v1_envelope_proto != nil {
		return
	}
	file_api_envelope_v1_envelope_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_envelope_v1_envelope_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_envelope_v1_envelope_proto_rawDesc), len(file_api_envelope_v1_envelope_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_envelope_v1_envelope_proto_goTypes,
		DependencyIndexes: file_api_envelope_v1_envelope_proto_depIdxs,
		EnumInfos:         file_api_envelope_v1_envelope_proto_enumTypes,
		MessageInfos:      file_api_envelope_v1_envelope_proto_msgTypes,
	}.Build()
	File_api_envelope_v1_envelope_proto = out.File
	file_api_envelope_v1_envelope_proto_goTypes = nil
	file_api_envelope_v1_envelope_proto_depIdxs = nil
}
