// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/events/v1/event.proto

// Package batch2go.events.v1 is the scientific event record schema: the primary
// evidence of every run. Observability metrics never testify (ARCHITECTURE §8.1).
//
// Wire compatibility is load-bearing. The hot path writes these messages with a
// hand-rolled, allocation-free encoder (internal/events/codec.go); the generated
// code here is the independent implementation that encoder is tested against.

package eventsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Emitter names the process that owns a timestamp. Ownership is evidence:
// t_cohort_seal belongs to the proxy at A=on and to the load generator at
// A=off, and the record says which (ADR-0001).
type Emitter int32

const (
	Emitter_EMITTER_UNSPECIFIED Emitter = 0
	Emitter_EMITTER_LOADGEN     Emitter = 1
	Emitter_EMITTER_PROXY       Emitter = 2
	Emitter_EMITTER_ADAPTER     Emitter = 3
	Emitter_EMITTER_TRITON      Emitter = 4
)

// Enum value maps for Emitter.
var (
	Emitter_name = map[int32]string{
		0: "EMITTER_UNSPECIFIED",
		1: "EMITTER_LOADGEN",
		2: "EMITTER_PROXY",
		3: "EMITTER_ADAPTER",
		4: "EMITTER_TRITON",
	}
	Emitter_value = map[string]int32{
		"EMITTER_UNSPECIFIED": 0,
		"EMITTER_LOADGEN":     1,
		"EMITTER_PROXY":       2,
		"EMITTER_ADAPTER":     3,
		"EMITTER_TRITON":      4,
	}
)

func (x Emitter) Enum() *Emitter {
	p := new(Emitter)
	*p = x
	return p
}

func (x Emitter) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Emitter) Descriptor() protoreflect.EnumDescriptor {
	return file_api_events_v1_event_proto_enumTypes[0].Descriptor()
}

func (Emitter) Type() protoreflect.EnumType {
	return &file_api_events_v1_event_proto_enumTypes[0]
}

func (x Emitter) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Emitter.Descriptor instead.
func (Emitter) EnumDescriptor() ([]byte, []int) {
	return file_api_events_v1_event_proto_rawDescGZIP(), []int{0}
}

// Status is the terminal outcome of a logical request. A timed-out member never
// disappears from the record (M2-PLAN §3, response integrity).
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_OK          Status = 1
	Status_STATUS_ERROR       Status = 2
	Status_STATUS_TIMEOUT     Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_OK",
		2: "STATUS_ERROR",
		3: "STATUS_TIMEOUT",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_OK":          1,
		"STATUS_ERROR":       2,
		"STATUS_TIMEOUT":     3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_api_events_v1_event_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_api_events_v1_event_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_api_events_v1_event_proto_rawDescGZIP(), []int{1}
}

// EventRecord is one process's contribution to the path of one logical request.
//
// Records are written append-only per process and joined offline by the
// validator on (run_id, cohort_id, ordinal) — at A=off a cohort is an accounting
// label and never a runtime object, while at A=on the proxy holds one to build
// the envelope (ADR-0001). Each of the 15 timestamps is optional: absence is
// typed by presence_mask, never encoded as zero (ADR-0005).
type EventRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ---- schema and run identity ----
	SchemaVersion uint32 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	ExperimentId  string `protobuf:"bytes,2,opt,name=experiment_id,json=experimentId,proto3" json:"experiment_id,omitempty"`
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string `protobuf:"bytes,4,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Cell          string `protobuf:"bytes,5,opt,name=cell,proto3" json:"cell,omitempty"`
	// clock_domain_id identifies the verified monotonic clock domain these
	// timestamps live in. Subtracting across domains is a validator error.
	ClockDomainId string  `protobuf:"bytes,6,opt,name=clock_domain_id,json=clockDomainId,proto3" json:"clock_domain_id,omitempty"`
	Emitter       Emitter `protobuf:"varint,7,opt,name=emitter,proto3,enum=batch2go.events.v1.Emitter" json:"emitter,omitempty"`
	WriterId      uint32  `protobuf:"varint,8,opt,name=writer_id,json=writerId,proto3" json:"writer_id,omitempty"`
	Seq           uint64  `protobuf:"varint,9,opt,name=seq,proto3" json:"seq,omitempty"`
	// ---- logical request identity ----
	CohortId        uint32 `protobuf:"varint,10,opt,name=cohort_id,json=cohortId,proto3" json:"cohort_id,omitempty"`
	Ordinal         uint32 `protobuf:"varint,11,opt,name=ordinal,proto3" json:"ordinal,omitempty"`
	EnvelopeId      uint64 `protobuf:"varint,12,opt,name=envelope_id,json=envelopeId,proto3" json:"envelope_id,omitempty"`
	ExecutionId     uint64 `protobuf:"varint,13,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	TritonRequestId string `protobuf:"bytes,14,opt,name=triton_request_id,json=tritonRequestId,proto3" json:"triton_request_id,omitempty"`
	// presence_mask has bit (i-1) set when timestamp i below is carried by this
	// record. The validator compares the join of all masks for a request against
	// the mask its cell topology requires.
	PresenceMask uint32 `protobuf:"varint,15,opt,name=presence_mask,json=presenceMask,proto3" json:"presence_mask,omitempty"`
	Status       Status `protobuf:"varint,16,opt,name=status,proto3,enum=batch2go.events.v1.Status" json:"status,omitempty"`
	// ---- the 15 timestamps, monotonic nanoseconds, direct clock reads ----
	TSched           *int64 `protobuf:"varint,20,opt,name=t_sched,json=tSched,proto3,oneof" json:"t_sched,omitempty"`                                 //  1 LoadGen  scheduled release
	TClientSend      *int64 `protobuf:"varint,21,opt,name=t_client_send,json=tClientSend,proto3,oneof" json:"t_client_send,omitempty"`                //  2 LoadGen  client send
	TProxyRecv       *int64 `protobuf:"varint,22,opt,name=t_proxy_recv,json=tProxyRecv,proto3,oneof" json:"t_proxy_recv,omitempty"`                   //  3 Proxy    X_req hop 1 end
	TCohortSeal      *int64 `protobuf:"varint,23,opt,name=t_cohort_seal,json=tCohortSeal,proto3,oneof" json:"t_cohort_seal,omitempty"`                //  4 LoadGen(A=off)/Proxy(A=on)
	TProxySend       *int64 `protobuf:"varint,24,opt,name=t_proxy_send,json=tProxySend,proto3,oneof" json:"t_proxy_send,omitempty"`                   //  5 Proxy    A_pack end
	TAdapterRecv     *int64 `protobuf:"varint,25,opt,name=t_adapter_recv,json=tAdapterRecv,proto3,oneof" json:"t_adapter_recv,omitempty"`             //  6 Adapter  X_req hop 2 end
	TAdapterDispatch *int64 `protobuf:"varint,26,opt,name=t_adapter_dispatch,json=tAdapterDispatch,proto3,oneof" json:"t_adapter_dispatch,omitempty"` //  7 Adapter  unpack end
	TQueueStart      *int64 `protobuf:"varint,27,opt,name=t_queue_start,json=tQueueStart,proto3,oneof" json:"t_queue_start,omitempty"`                //  8 Triton   Q_backend start
	TComputeStart    *int64 `protobuf:"varint,28,opt,name=t_compute_start,json=tComputeStart,proto3,oneof" json:"t_compute_start,omitempty"`          //  9 Triton   S_comp start
	TComputeEnd      *int64 `protobuf:"varint,29,opt,name=t_compute_end,json=tComputeEnd,proto3,oneof" json:"t_compute_end,omitempty"`                // 10 Triton   S_comp end
	TAdapterResult   *int64 `protobuf:"varint,30,opt,name=t_adapter_result,json=tAdapterResult,proto3,oneof" json:"t_adapter_result,omitempty"`       // 11 Adapter  backend return
	TAdapterSend     *int64 `protobuf:"varint,31,opt,name=t_adapter_send,json=tAdapterSend,proto3,oneof" json:"t_adapter_send,omitempty"`             // 12 Adapter  response pack end
	TProxyRespRecv   *int64 `protobuf:"varint,32,opt,name=t_proxy_resp_recv,json=tProxyRespRecv,proto3,oneof" json:"t_proxy_resp_recv,omitempty"`     // 13 Proxy    X_resp end
	TProxyFanout     *int64 `protobuf:"varint,33,opt,name=t_proxy_fanout,json=tProxyFanout,proto3,oneof" json:"t_proxy_fanout,omitempty"`             // 14 Proxy    F_fanout end
	TClientRecv      *int64 `protobuf:"varint,34,opt,name=t_client_recv,json=tClientRecv,proto3,oneof" json:"t_client_recv,omitempty"`                // 15 LoadGen  client completion
	// ---- byte accounting and execution evidence ----
	LogicalBytes  uint32 `protobuf:"varint,40,opt,name=logical_bytes,json=logicalBytes,proto3" json:"logical_bytes,omitempty"`
	EnvelopeBytes uint32 `protobuf:"varint,41,opt,name=envelope_bytes,json=envelopeBytes,proto3" json:"envelope_bytes,omitempty"`
	// batch_size is b_kj: the shape of the execution this request belonged to, as
	// reported by the backend. Declared V is never inferred from it.
	BatchSize uint32 `protobuf:"varint,42,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	// membership_uids is the self-attesting evidence of ADR-0007: the complete uid
	// set the model returned for this request's execution. Own-uid-only echo is a
	// failure, not a pass.
	MembershipUids []int64 `protobuf:"varint,43,rep,packed,name=membership_uids,json=membershipUids,proto3" json:"membership_uids,omitempty"`
	// membership_count is the size the responding execution claimed. It exceeds
	// len(membership_uids) only when the record hit its fixed capacity, which the
	// validator reports as truncated evidence rather than accepting silently.
	MembershipCount uint32 `protobuf:"varint,44,opt,name=membership_count,json=membershipCount,proto3" json:"membership_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventRecord) Reset() {
	*x = EventRecord{}
	mi := &file_api_events_v1_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRecord) ProtoMessage() {}

func (x *EventRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_events_v1_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRecord.ProtoReflect.Descriptor instead.
func (*EventRecord) Descriptor() ([]byte, []int) {
	return file_api_events_v1_event_proto_rawDescGZIP(), []int{0}
}

func (x *EventRecord) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *EventRecord) GetExperimentId() string {
	if x != nil {
		return x.ExperimentId
	}
	return ""
}

func (x *EventRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EventRecord) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *EventRecord) GetCell() string {
	if x != nil {
		return x.Cell
	}
	return ""
}

func (x *EventRecord) GetClockDomainId() string {
	if x != nil {
		return x.ClockDomainId
	}
	return ""
}

func (x *EventRecord) GetEmitter() Emitter {
	if x != nil {
		return x.Emitter
	}
	return Emitter_EMITTER_UNSPECIFIED
}

func (x *EventRecord) GetWriterId() uint32 {
	if x != nil {
		return x.WriterId
	}
	return 0
}

func (x *EventRecord) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *EventRecord) GetCohortId() uint32 {
	if x != nil {
		return x.CohortId
	}
	return 0
}

func (x *EventRecord) GetOrdinal() uint32 {
	if x != nil {
		return x.Ordinal
	}
	return 0
}

func (x *EventRecord) GetEnvelopeId() uint64 {
	if x != nil {
		return x.EnvelopeId
	}
	return 0
}

func (x *EventRecord) GetExecutionId() uint64 {
	if x != nil {
		return x.ExecutionId
	}
	return 0
}

func (x *EventRecord) GetTritonRequestId() string {
	if x != nil {
		return x.TritonRequestId
	}
	return ""
}

func (x *EventRecord) GetPresenceMask() uint32 {
	if x != nil {
		return x.PresenceMask
	}
	return 0
}

func (x *EventRecord) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *EventRecord) GetTSched() int64 {
	if x != nil && x.TSched != nil {
		return *x.TSched
	}
	return 0
}

func (x *EventRecord) GetTClientSend() int64 {
	if x != nil && x.TClientSend != nil {
		return *x.TClientSend
	}
	return 0
}

func (x *EventRecord) GetTProxyRecv() int64 {
	if x != nil && x.TProxyRecv != nil {
		return *x.TProxyRecv
	}
	return 0
}

func (x *EventRecord) GetTCohortSeal() int64 {
	if x != nil && x.TCohortSeal != nil {
		return *x.TCohortSeal
	}
	return 0
}

func (x *EventRecord) GetTProxySend() int64 {
	if x != nil && x.TProxySend != nil {
		return *x.TProxySend
	}
	return 0
}

func (x *EventRecord) GetTAdapterRecv() int64 {
	if x != nil && x.TAdapterRecv != nil {
		return *x.TAdapterRecv
	}
	return 0
}

func (x *EventRecord) GetTAdapterDispatch() int64 {
	if x != nil && x.TAdapterDispatch != nil {
		return *x.TAdapterDispatch
	}
	return 0
}

func (x *EventRecord) GetTQueueStart() int64 {
	if x != nil && x.TQueueStart != nil {
		return *x.TQueueStart
	}
	return 0
}

func (x *EventRecord) GetTComputeStart() int64 {
	if x != nil && x.TComputeStart != nil {
		return *x.TComputeStart
	}
	return 0
}

func (x *EventRecord) GetTComputeEnd() int64 {
	if x != nil && x.TComputeEnd != nil {
		return *x.TComputeEnd
	}
	return 0
}

func (x *EventRecord) GetTAdapterResult() int64 {
	if x != nil && x.TAdapterResult != nil {
		return *x.TAdapterResult
	}
	return 0
}

func (x *EventRecord) GetTAdapterSend() int64 {
	if x != nil && x.TAdapterSend != nil {
		return *x.TAdapterSend
	}
	return 0
}

func (x *EventRecord) GetTProxyRespRecv() int64 {
	if x != nil && x.TProxyRespRecv != nil {
		return *x.TProxyRespRecv
	}
	return 0
}

func (x *EventRecord) GetTProxyFanout() int64 {
	if x != nil && x.TProxyFanout != nil {
		return *x.TProxyFanout
	}
	return 0
}

func (x *EventRecord) GetTClientRecv() int64 {
	if x != nil && x.TClientRecv != nil {
		return *x.TClientRecv
	}
	return 0
}

func (x *EventRecord) GetLogicalBytes() uint32 {
	if x != nil {
		return x.LogicalBytes
	}
	return 0
}

func (x *EventRecord) GetEnvelopeBytes() uint32 {
	if x != nil {
		return x.EnvelopeBytes
	}
	return 0
}

func (x *EventRecord) GetBatchSize() uint32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

func (x *EventRecord) GetMembershipUids() []int64 {
	if x != nil {
		return x.MembershipUids
	}
	return nil
}

func (x *EventRecord) GetMembershipCount() uint32 {
	if x != nil {
		return x.MembershipCount
	}
	return 0
}

var File_api_events_v1_event_proto protoreflect.FileDescriptor

const file_api_events_v1_event_proto_rawDesc = "" +
	"\n" +
	"\x19api/events/v1/event.proto\x12\x12batch2go.events.v1\"\x84\r\n" +
	"\vEventRecord\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x12#\n" +
	"\rexperiment_id\x18\x02 \x01(\tR\fexperimentId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x04 \x01(\tR\x05runId\x12\x12\n" +
	"\x04cell\x18\x05 \x01(\tR\x04cell\x12&\n" +
	"\x0fclock_domain_id\x18\x06 \x01(\tR\rclockDomainId\x125\n" +
	"\aemitter\x18\a \x01(\x0e2\x1b.batch2go.events.v1.EmitterR\aemitter\x12\x1b\n" +
	"\twriter_id\x18\b \x01(\rR\bwriterId\x12\x10\n" +
	"\x03seq\x18\t \x01(\x04R\x03seq\x12\x1b\n" +
	"\tcohort_id\x18\n" +
	" \x01(\rR\bcohortId\x12\x18\n" +
	"\aordinal\x18\v \x01(\rR\aordinal\x12\x1f\n" +
	"\venvelope_id\x18\f \x01(\x04R\n" +
	"envelopeId\x12!\n" +
	"\fexecution_id\x18\r \x01(\x04R\vexecutionId\x12*\n" +
	"\x11triton_request_id\x18\x0e \x01(\tR\x0ftritonRequestId\x12#\n" +
	"\rpresence_mask\x18\x0f \x01(\rR\fpresenceMask\x122\n" +
	"\x06status\x18\x10 \x01(\x0e2\x1a.batch2go.events.v1.StatusR\x06status\x12\x1c\n" +
	"\at_sched\x18\x14 \x01(\x03H\x00R\x06tSched\x88\x01\x01\x12'\n" +
	"\rt_client_send\x18\x15 \x01(\x03H\x01R\vtClientSend\x88\x01\x01\x12%\n" +
	"\ft_proxy_recv\x18\x16 \x01(\x03H\x02R\n" +
	"tProxyRecv\x88\x01\x01\x12'\n" +
	"\rt_cohort_seal\x18\x17 \x01(\x03H\x03R\vtCohortSeal\x88\x01\x01\x12%\n" +
	"\ft_proxy_send\x18\x18 \x01(\x03H\x04R\n" +
	"tProxySend\x88\x01\x01\x12)\n" +
	"\x0et_adapter_recv\x18\x19 \x01(\x03H\x05R\ftAdapterRecv\x88\x01\x01\x121\n" +
	"\x12t_adapter_dispatch\x18\x1a \x01(\x03H\x06R\x10tAdapterDispatch\x88\x01\x01\x12'\n" +
	"\rt_queue_start\x18\x1b \x01(\x03H\aR\vtQueueStart\x88\x01\x01\x12+\n" +
	"\x0ft_compute_start\x18\x1c \x01(\x03H\bR\rtComputeStart\x88\x01\x01\x12'\n" +
	"\rt_compute_end\x18\x1d \x01(\x03H\tR\vtComputeEnd\x88\x01\x01\x12-\n" +
	"\x10t_adapter_result\x18\x1e \x01(\x03H\n" +
	"R\x0etAdapterResult\x88\x01\x01\x12)\n" +
	"\x0et_adapter_send\x18\x1f \x01(\x03H\vR\ftAdapterSend\x88\x01\x01\x12.\n" +
	"\x11t_proxy_resp_recv\x18  \x01(\x03H\fR\x0etProxyRespRecv\x88\x01\x01\x12)\n" +
	"\x0et_proxy_fanout\x18! \x01(\x03H\rR\ftProxyFanout\x88\x01\x01\x12'\n" +
	"\rt_client_recv\x18\" \x01(\x03H\x0eR\vtClientRecv\x88\x01\x01\x12#\n" +
	"\rlogical_bytes\x18( \x01(\rR\flogicalBytes\x12%\n" +
	"\x0eenvelope_bytes\x18) \x01(\rR\renvelopeBytes\x12\x1d\n" +
	"\n" +
	"batch_size\x18* \x01(\rR\tbatchSize\x12+\n" +
	"\x0fmembership_uids\x18+ \x03(\x03B\x02\x10\x01R\x0emembershipUids\x12)\n" +
	"\x10membership_count\x18, \x01(\rR\x0fmembershipCountB\n" +
	"\n" +
	"\b_t_schedB\x10\n" +
	"\x0e_t_client_sendB\x0f\n" +
	"\r_t_proxy_recvB\x10\n" +
	"\x0e_t_cohort_sealB\x0f\n" +
	"\r_t_proxy_sendB\x11\n" +
	"\x0f_t_adapter_recvB\x15\n" +
	"\x13_t_adapter_dispatchB\x10\n" +
	"\x0e_t_queue_startB\x12\n" +
	"\x10_t_compute_startB\x10\n" +
	"\x0e_t_compute_endB\x13\n" +
	"\x11_t_adapter_resultB\x11\n" +
	"\x0f_t_adapter_sendB\x14\n" +
	"\x12_t_proxy_resp_recvB\x11\n" +
	"\x0f_t_proxy_fanoutB\x10\n" +
	"\x0e_t_client_recv*s\n" +
	"\aEmitter\x12\x17\n" +
	"\x13EMITTER_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fEMITTER_LOADGEN\x10\x01\x12\x11\n" +
	"\rEMITTER_PROXY\x10\x02\x12\x13\n" +
	"\x0fEMITTER_ADAPTER\x10\x03\x12\x12\n" +
	"\x0eEMITTER_TRITON\x10\x04*U\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tSTATUS_OK\x10\x01\x12\x10\n" +
	"\fSTATUS_ERROR\x10\x02\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x03B9Z7github.com/matthewhoung/batch2go/api/events/v1;eventsv1b\x06proto3"

var (
	file_api_events_v1_event_proto_rawDescOnce sync.Once
	file_api_events_v1_event_proto_rawDescData []byte
)

func file_api_events_v1_event_proto_rawDescGZIP() []byte {
	file_api_events_v1_event_proto_rawDescOnce.Do(func() {
		file_api_events_v1_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_events_v1_event_proto_rawDesc), len(file_api_events_v1_event_proto_rawDesc)))
	})
	return file_api_events_v1_event_proto_rawDescData
}

var file_api_events_v1_event_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_events_v1_event_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_events_v1_event_proto_goTypes = []any{
	(Emitter)(0),        // 0: batch2go.events.v1.Emitter
	(Status)(0),         // 1: batch2go.events.v1.Status
	(*EventRecord)(nil), // 2: batch2go.events.v1.EventRecord
}
var file_api_events_v1_event_proto_depIdxs = []int32{
	0, // 0: batch2go.events.v1.EventRecord.emitter:type_name -> batch2go.events.v1.Emitter
	1, // 1: batch2go.events.v1.EventRecord.status:type_name -> batch2go.events.v1.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_events_v1_event_proto_init() }
func file_api_events_v1_event_proto_init() {
	if File_api_events_v1_event_proto != nil {
		return
	}
	file_api_events_v1_event_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_events_v1_event_proto_rawDesc), len(file_api_events_v1_event_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_events_v1_event_proto_goTypes,
		DependencyIndexes: file_api_events_v1_event_proto_depIdxs,
		EnumInfos:         file_api_events_v1_event_proto_enumTypes,
		MessageInfos:      file_api_events_v1_event_proto_msgTypes,
	}.Build()
	File_api_events_v1_event_proto = out.File
	file_api_events_v1_event_proto_goTypes = nil
	file_api_events_v1_event_proto_depIdxs = nil
}
