"""Generate synthetic model artifacts and record them in the artifact catalog.

Usage:
    python -m batch2go_modelgen --out-dir <dir> --catalog <catalog.json> \
        --kappa 8 --payload-mib 0.25

Writes one .onnx per requested variant and a catalog manifest describing each:
artifact id, digest, graph identity, and I/O schema. The catalog is what the
runner verifies a model against before Triton loads it, so that the model
actually serving is provably the model the manifest named.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from batch2go_modelgen.synthetic import (
    FEATURE_WIDTH,
    OPSET,
    PRODUCER_NAME,
    PRODUCER_VERSION,
    ModelSpec,
    build_model,
    digest,
    serialize,
)

CATALOG_SCHEMA_VERSION = 1

BYTES_PER_MIB = 1024 * 1024
BYTES_PER_FLOAT32 = 4


def payload_floats_for(payload_mib: float) -> int:
    """Padding width in float32 elements for a per-request payload in MiB."""
    total = int(round(payload_mib * BYTES_PER_MIB))
    if total % BYTES_PER_FLOAT32 != 0:
        raise ValueError(f"payload of {payload_mib} MiB is not a whole number of float32 elements")
    floats = total // BYTES_PER_FLOAT32
    if floats < 1:
        raise ValueError(f"payload of {payload_mib} MiB leaves no padding elements")
    return floats


def catalog_entry(spec: ModelSpec, payload: bytes, payload_mib: float) -> dict:
    """Provenance for one artifact: what it is, and what produced it."""
    uid_set_dims = ["N", "N"] if spec.attest else ["N", 1]
    return {
        "artifact_id": spec.name,
        "digest": digest(payload),
        "bytes": len(payload),
        "precision": "fp32",
        "membership_evidence": "self_attesting" if spec.attest else "own_uid_echo",
        "generator": {
            "producer": PRODUCER_NAME,
            "producer_version": PRODUCER_VERSION,
            "opset": OPSET,
            "ir_version": 9,
        },
        "graph": {
            "kappa": spec.kappa,
            "kappa_semantics": "repeated-block count, dimensionless (ADR-0002)",
            "feature_width": spec.feature_width,
            "payload_floats": spec.payload_floats,
            "payload_mib": payload_mib,
        },
        "io": {
            "inputs": [
                {"name": "data", "data_type": "FP32", "dims": ["N", spec.feature_width]},
                {"name": "padding", "data_type": "FP32", "dims": ["N", spec.payload_floats]},
                {"name": "uid", "data_type": "INT64", "dims": ["N", 1]},
            ],
            "outputs": [
                {"name": "data_out", "data_type": "FP32", "dims": ["N", spec.feature_width]},
                {"name": "uid_set", "data_type": "INT64", "dims": uid_set_dims},
            ],
        },
        # Realized milliseconds are a per-environment measurement, never a
        # property of the artifact (ADR-0002).
        "kappa_profile": {"realized_ms": None, "measured_on": None},
    }


def main() -> int:
    parser = argparse.ArgumentParser(prog="batch2go-modelgen", description=__doc__)
    parser.add_argument("--out-dir", type=Path, required=True, help="where .onnx artifacts are written")
    parser.add_argument("--catalog", type=Path, required=True, help="catalog manifest to write")
    parser.add_argument("--kappa", type=int, default=8, help="repeated-block count")
    parser.add_argument("--payload-mib", type=float, default=0.25, help="per-request payload in MiB")
    parser.add_argument("--feature-width", type=int, default=FEATURE_WIDTH)
    parser.add_argument(
        "--no-counter-fixture",
        action="store_true",
        help="skip the naive-echo variant (it is a permanent test fixture; generated by default)",
    )
    args = parser.parse_args()

    payload_floats = payload_floats_for(args.payload_mib)
    variants = [True] if args.no_counter_fixture else [True, False]

    args.out_dir.mkdir(parents=True, exist_ok=True)
    args.catalog.parent.mkdir(parents=True, exist_ok=True)

    entries = []
    for attest in variants:
        spec = ModelSpec(
            kappa=args.kappa,
            payload_floats=payload_floats,
            feature_width=args.feature_width,
            attest=attest,
        )
        blob = serialize(build_model(spec))
        path = args.out_dir / f"{spec.name}.onnx"
        path.write_bytes(blob)
        entries.append(catalog_entry(spec, blob, args.payload_mib))
        print(f"wrote {path} ({len(blob)} bytes) {entries[-1]['digest']}")

    catalog = {
        "schema_version": CATALOG_SCHEMA_VERSION,
        "artifacts": sorted(entries, key=lambda e: e["artifact_id"]),
    }
    args.catalog.write_text(json.dumps(catalog, indent=2, sort_keys=True) + "\n")
    print(f"wrote {args.catalog} ({len(entries)} artifacts)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
